{
 "title": "Pizza Dashboard Deployment",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "new_memory_total_percent{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "new_cpu_total_percent{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(authentication_success_total{service_name=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(authentication_failure_total{service_name=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "current_users_total_ratio{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(requests_total{service_name=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "all"
    },
    {
     "expr": "rate(requests_delete_total{service_name=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(requests_get_total{service_name=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(requests_post_total{service_name=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "post"
    },
    {
     "expr": "rate(requests_put_total{service_name=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "request_latency_milliseconds{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(pizza_success_total{service_name=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza purchases"
    },
    {
     "expr": "rate(pizza_failures_total{service_name=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Purchase failures"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "new_revenue_total{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pizza_latency_milliseconds{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Latency"
    }
   ]
  }
 ]
}